export {default as App} from './App';
export {default as Home} from './Home';
export {default as MyProfile} from './MyProfile';
export {default as DeletePost} from './DeletePost';
export {default as AccountForm} from './AccountForm';
export {default as Logout} from './Logout';
export {default as AddPosts} from './AddPosts'
export {default as Search} from './Search';
export {default as PostView} from './PostView'